// Generated by attribution — do not edit. Regenerate with `attribution apply`.
// This wrapper keeps attribution configuration deterministic across expo prebuild --clean.
const withAttribution = require("@attributionkit/expo/app.plugin.js");

const options = {
  "endpoint": "https://attribution.sh/",
  "associatedDomains": [],
  "publisherMode": false,
  "skAdNetworkIds": [],
  "events": [
    "install",
    "trial",
    "purchase",
    "retention"
  ],
  "schemaHash": "3d8ac4b627c9ac1bfdbe44231ce4261f3a31eaa5f784c52f0f29d48a52481074",
  "disableMetaConversionReporting": false
};

module.exports = function withAttributionConfigured(config) {
  return withAttribution(config, options);
};
