// Generated by attribution — do not edit. Regenerate with `attribution apply`.
import { Attribution, type AttributionConsentState } from "@attributionkit/expo";

export const attributionEvents = ["install", "trial", "purchase", "retention"] as const;
export type AttributionEvent = (typeof attributionEvents)[number];
export interface AttributionEventProperties {
  install: Record<string, never>;
  trial: Record<string, never>;
  purchase: Record<string, never>;
  retention: Record<string, never>;
}

export function trackAttributionEvent<Event extends AttributionEvent>(
  event: Event,
  properties: AttributionEventProperties[Event] = {} as AttributionEventProperties[Event],
  consentState: AttributionConsentState = "unknown",
): Promise<void> {
  return Attribution.track(event, properties, consentState);
}
